package com.kai.mavenspring.mybatis.model;

public class Favorate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.FAVORATE.ID
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.FAVORATE.NAME
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.FAVORATE.LOCATION
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.FAVORATE.ADDRESS
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.FAVORATE.TEL
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.FAVORATE.URL
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.FAVORATE.ID
     *
     * @return the value of TEST.FAVORATE.ID
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.FAVORATE.ID
     *
     * @param id the value for TEST.FAVORATE.ID
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.FAVORATE.NAME
     *
     * @return the value of TEST.FAVORATE.NAME
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.FAVORATE.NAME
     *
     * @param name the value for TEST.FAVORATE.NAME
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.FAVORATE.LOCATION
     *
     * @return the value of TEST.FAVORATE.LOCATION
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.FAVORATE.LOCATION
     *
     * @param location the value for TEST.FAVORATE.LOCATION
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.FAVORATE.ADDRESS
     *
     * @return the value of TEST.FAVORATE.ADDRESS
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.FAVORATE.ADDRESS
     *
     * @param address the value for TEST.FAVORATE.ADDRESS
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.FAVORATE.TEL
     *
     * @return the value of TEST.FAVORATE.TEL
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.FAVORATE.TEL
     *
     * @param tel the value for TEST.FAVORATE.TEL
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.FAVORATE.URL
     *
     * @return the value of TEST.FAVORATE.URL
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.FAVORATE.URL
     *
     * @param url the value for TEST.FAVORATE.URL
     *
     * @mbggenerated Thu Jan 12 22:19:50 CST 2012
     */
    public void setUrl(String url) {
        this.url = url;
    }
}